name: CI

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run linting
        run: npm run lint

      - name: Run knip check
        run: npm run knip

      - name: Run tests
        run: npm run test:run

      - name: Build project
        run: npm run build

      - name: Create zip archive
        run: zip -r chat-connect.zip dist/

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: chat-connect
          path: chat-connect.zip
