name: CI

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check:
    name: Check & build

    runs-on: ubuntu-latest

    container:
      image: mcr.microsoft.com/playwright:v1.53.1-noble

    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run type checking
        run: npm run tsc

      - name: Run linting
        run: npm run lint

      - name: Run knip check
        run: npm run knip

      - name: Run tests
        run: npm run test:coverage

      - name: Report Coverage
        if: always()
        uses: davelosert/vitest-coverage-report-action@v2

      - name: Build project
        run: npm run build

      - name: Upload build artifact
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v4
        with:
          name: chat-connect
          path: dist
          if-no-files-found: error
          overwrite: true

  release:
    name: Create release
    needs: check

    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    permissions:
      contents: write

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: chat-connect
          path: dist

      - name: Compress build
        run: cd dist && zip -r ../chat-connect.zip .

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          files: chat-connect.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
